### ISSUE TITLE
每天的下载限制是几次呢，是3次吗？

### ISSUE THREAD

**Issue by lulu002** [hsowan/CSDNBot#2]
原理是不是在服务端 你使用你的csdn帐号模拟 下载，再返回给用户呢？

**Comment by hsowan** [comment]
每天3次(发你邮件了)

**Comment by hsowan** [comment]
原理是你说的那样

**Comment by lulu002** [comment]
谢谢你的这个服务。做得很赞。

**Comment by lulu002** [comment]
> 原理是不是在服务端 你使用你的csdn帐号模拟 下载，再返回给用户呢？



> 每天3次(发你邮件了)

请问这个服务会一起免费吗？

**Comment by hsowan** [comment]
> > 原理是不是在服务端 你使用你的csdn帐号模拟 下载，再返回给用户呢？
> 
> > 每天3次(发你邮件了)
> 
> 请问这个服务会一起免费吗？

直至 2019-09-13 或 VIP账号下载数用尽

**Comment by hsowan** [comment]
资源有限请善用
